routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/', 'Home')->name('home');
Route::get('/dashboard', 'Dashboard')->name('dashboard')->middleware('auth');

Route::get('user/projects', 'UserProjectController@project')->name('user.project');
Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('/profile/update', 'ProfileController@update')->name('profile.update');
Route::get('/profile/edit/password', 'ProfileController@editPassword')->name('profile.password.edit');
Route::put('/profile/update/password', 'ProfileController@updatePassword')->name('profile.password.update');


Route::resource('leave', 'LeaveController');
Route::resource('status', 'StatusController')->except(['create', 'store']);
Route::resource('user', 'UserController');
Route::resource('project', 'ProjectController');
Route::resource('article', 'ArticleController');
Route::resource('category', 'CategoryController');
Route::resource('article-status', 'ArticleStatusController')->except(['create', 'store', 'edit', 'update']);

Route::put('article-status/{status}/accept', 'ArticleStatusController@accept')->name('article-status.accept');
Route::put('article-status/{status}/cancel', 'ArticleStatusController@cancel')->name('article-status.cancel');
Route::put('status/{status}/approve', 'StatusController@approve')->name('status.approve');
Route::put('status/{status}/decline', 'StatusController@decline')->name('status.decline');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
    protected $table = 'projects';

    protected $fillable = [
        'name',
        'description',
        'status',
        'value',
        'start',
        'end',
    ];

    public function user() {
        return $this->belongsToMany(User::class, 'projects_users', 'project_id', 'user_id');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Project\Store;
use App\Project;
use App\Tables\ProjectTableView;
use App\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Response;
use Illuminate\View\View;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return ProjectTableView
     */
    public function index()
    {
        //
        $project = Project::paginate();
        return (ProjectTableView::make($project))->view('project.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        //
        $user = User::all()->pluck('name', 'id');
        return view('project.create', ['user' => $user]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return Response
     */
    public function store(Store $request)
    {
        //
        $project = Project::create($request->all());
        $project->user()->attach($request->user);

        return redirect()->back()->withSuccess('A new project has been added!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|Response|View
     */
    public function show($id)
    {
        //
        $project = Project::find($id);
        $user = $project->user->implode('name', ', ');
        return view('project.show', compact('project', 'user'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|Response|View
     */
    public function edit($id)
    {
        //
        $project = Project::find($id);
        $user = User::all()->pluck('name', 'id');
        return view('project.edit', compact('project', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return Response
     */
    public function update(Store $request, $id)
    {
        //
        $input = $request->all();
        $project = Project::find($id);
        $project->update($input);
        $project->user()->sync($request->user);

        return redirect()->back()->withSuccess('This project has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
        $project = Project::find($id);
        $project->delete();

        return redirect()->back()->withSuccess('A project has been deleted!');
    }
}

resources/views/project/create.blade.php
@extends('vendor.laravolt.layouts.app')
@section('content')
    <x-titlebar title="Add New Project">
        <x-backlink url="{{ route('project.index') }}"></x-backlink>
    </x-titlebar>

    <x-panel>
        {!! form()->post(route('project.store'))->attribute('autocomplete', 'off')->horizontal() !!}
        {!! form()->text('name')->placeholder('Project Name')->label('Project Name') !!}
        {!! form()->textarea('description')->placeholder('Project Description')->label('Description') !!}
        {!! form()->datepicker('start')->label('Project Starting Date')->placeholder('Starting Date') !!}
        {!! form()->datepicker('end')->label('Project End Date')->placeholder('End Date') !!}
        {!! form()->text('text')->label('Text') !!}

        {!! form()->dropdown('status', [
        'prospect' => 'Prospect',
        'in progress' => 'In Progress',
        'finished' => 'Finished',
        ])->label('Project Status')->placeholder('Choose Project Status') !!}
        {!! form()->text('value')->label('Project Value') !!}

        {!! form()->checkboxGroup('user', $user)->label('Team Member') !!}

        {!! form()->action(
            form()->submit(__('laravolt::action.save')),
            form()->link(__('laravolt::action.back'), route('project.index'))) !!}
        {!! form()->close() !!}
    </x-panel>
@stop

resources/views/project/edit.blade.php
@extends('vendor.laravolt.layouts.app')
@section('content')
    <x-titlebar title="Edit {{ $project->name }}">
        <x-backlink url="{{ route('project.index') }}"></x-backlink>
    </x-titlebar>

    <x-panel>
        {!! form()->bind($project)->open()->put()->action(route('project.update', $project->id))->horizontal()->attribute('autocomplete', 'off') !!}
        {!! form()->text('name')->placeholder('Project Name')->label('Project Name') !!}
        {!! form()->textarea('description')->placeholder('Project Description')->label('Description') !!}
        {!! form()->datepicker('start')->label('Project Starting Date')->placeholder('Starting Date') !!}
        {!! form()->datepicker('end')->label('Project End Date')->placeholder('End Date') !!}

        {!! form()->dropdown('status', [
        'prospect' => 'Prospect',
        'in progress' => 'In Progress',
        'finished' => 'Finished',
        ])->label('Project Status')->placeholder('Choose Project Status') !!}
        {!! form()->text('value')->label('Project Value') !!}

        {!! form()->checkboxGroup('user', $user)->label('Team Member') !!}

        {!! form()->action(
            form()->submit(__('laravolt::action.save')),
            form()->link(__('laravolt::action.back'), route('project.index'))) !!}
        {!! form()->close() !!}
    </x-panel>
@stop

resources/views/project/index.blade.php
@extends('vendor.laravolt.layouts.app')
@section('content')
    <x-titlebar title="Project">
        <div class="item">
            <x-link url="{{ route('project.create') }}">
                <i class="icon plus"></i> @lang('laravolt::action.add')
            </x-link>
        </div>
    </x-titlebar>

    {!! $table !!}
@stop

resources/views/project/show.blade.php
@extends('vendor.laravolt.layouts.app')
@section('content')
    <x-titlebar title="{{ $project->name }}">
        <x-backlink url="{{ route('project.index') }}"></x-backlink>
    </x-titlebar>

    <x-panel>
        {!! form()->open()->horizontal() !!}
        {!! form()->text('name', $project->name)->label('Project Name')->disable() !!}
        {!! form()->textarea('description', $project->description)->label('Description')->disable() !!}
        {!! form()->text('start', date('d F Y', strtotime($project->start)))->label('Starting Date')->disable() !!}
        {!! form()->text('start', date('d F Y', strtotime($project->end)))->label('Project End Date')->disable() !!}
        {!! form()->text('status', strtoupper($project->status))->label('Project Status')->disable() !!}
        {!! form()->text('value', "Rp. " . number_format($project->value))->label('Project Value')->disable() !!}
        {!! form()->text('user', $user)->label('Team Member')->disable() !!}

        {!! form()->close() !!}
    </x-panel>
@stop