routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/', 'Home')->name('home');
Route::get('/dashboard', 'Dashboard')->name('dashboard')->middleware('auth');

Route::get('user/projects', 'UserProjectController@project')->name('user.project');
Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('/profile/update', 'ProfileController@update')->name('profile.update');
Route::get('/profile/edit/password', 'ProfileController@editPassword')->name('profile.password.edit');
Route::put('/profile/update/password', 'ProfileController@updatePassword')->name('profile.password.update');


Route::resource('leave', 'LeaveController');
Route::resource('status', 'StatusController')->except(['create', 'store']);
Route::resource('user', 'UserController');
Route::resource('project', 'ProjectController');
Route::resource('article', 'ArticleController');
Route::resource('category', 'CategoryController');
Route::resource('article-status', 'ArticleStatusController')->except(['create', 'store', 'edit', 'update']);

Route::put('article-status/{status}/accept', 'ArticleStatusController@accept')->name('article-status.accept');
Route::put('article-status/{status}/cancel', 'ArticleStatusController@cancel')->name('article-status.cancel');
Route::put('status/{status}/approve', 'StatusController@approve')->name('status.approve');
Route::put('status/{status}/decline', 'StatusController@decline')->name('status.decline');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    //
    protected $table = 'articles';

    protected $fillable = [
        'title',
        'content',
        'image',
        'category_id',
        'status',
        'created_by',
        'updated_by'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    use SoftDeletes;

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Category;
use App\Tables\ArticleTableView;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return ArticleTableView
     */
    public function index()
    {
        //
        $getArticleOfUser = Auth::user()->article;
        return (ArticleTableView::make($getArticleOfUser))->view('article.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        //
        $category = Category::pluck('name', 'id');
        return view('article.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
        $article = $request->all();
        $article['created_by'] = Auth::user()->id;
        $article['updated_by'] = Auth::user()->id;

        $article['image'] = $article['image']->store('uploads', 'public');


        Article::create($article);

        return redirect()->back()->withSuccess('A new article has been made successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function show($id)
    {
        //
        $article = Article::find($id);
        return view('article.show', ['article' => $article]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function edit($id)
    {
        //
        $article = Article::find($id);
        $category = Category::pluck('name', 'id');
        return view('article.edit', ['article' => $article, 'category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
        $article = $request->all();
        $article['updated_by'] = Auth::user()->id;

        if ($request->hasFile('image')) {
            Storage::delete(public_path('storage/' . $article['image']));
            $article['image'] = $article['image']->store('uploads', 'public');
        } else {
            $article['image'] = Article::find($id)->image;
        }

        Article::find($id)->update($article);

        return redirect()->back()->withSuccess('This article has been updated successfully!');
    }
}

resources/views/article/_form.blade.php
	{!! form()->text('title')->label('Title') !!}
	{!! form()->textarea('content')->label('Content') !!}
	{!! form()->file('image')->label('Insert Image') !!}
    {!! form()->select('category_id', $category)->label('Categories')->placeholder('Choose category') !!}

{!! form()->action([
    form()->submit('Simpan'),
    form()->link('Batal', route('article.index'))
]) !!}

resources/views/article/create.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-backlink url="{{ route('article.index') }}"></x-backlink>

    <x-panel title="Tambah Article">
        {!! form()->post(route('article.store'))->horizontal()->multipart() !!}
        @include('article._form')
        {!! form()->close() !!}
    </x-panel>

@stop

resources/views/article/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <x-titlebar title="Edit {{ $article->title }}">
        <x-backlink url="{{ route('article.index') }}"></x-backlink>
    </x-titlebar>

    <x-panel title="">
        {!! form()->bind($article)->put(route('article.update', $article->getKey()))->horizontal()->multipart() !!}
        {!! form()->text('title', $article->title)->label('Title')!!}
        {!! form()->textarea('content', $article->content)->label('Content') !!}
        {!! form()->select('category_id', $category)->label('Categories')->placeholder('Choose category') !!}
        <img src="{{ asset('storage/'.$article->image) }}" alt="image" class="ui centered medium image">

        <div class="ui divider hidden"></div>

        {!! form()->file('image')->label('Insert Image') !!}

        <div class="ui divider section"></div>

        {!! form()->action([
            form()->submit('Simpan'),
            form()->link('Batal', route('category.index'))
        ]) !!}
        {!! form()->close() !!}
    </x-panel>

@stop

resources/views/article/index.blade.php
@extends('laravolt::layouts.app')

@section('content')


    <x-titlebar title="Article">
        <x-item>
            <x-link label="Tambah" icon="plus" url="{{ route('article.create') }}"></x-link>
        </x-item>
    </x-titlebar>

    {!! $table !!}
@stop

resources/views/article/show.blade.php
@extends('laravolt::layouts.app')

@section('content')
    <x-titlebar title="">
        <x-backlink url="{{ route('article.index') }}"></x-backlink>
    </x-titlebar>

    <x-panel title="{{ $article->title }}">
        <div class="ui grid">
            <div class="four wide column">
                <img src="{{ asset('storage/'.$article->image) }}" alt="image" class="ui centered medium image">
            </div>

            <div class="twelve wide column">
                <p>
                    {{ $article->content }}
                </p>
            </div>
        </div>

        <div class="ui divider section"></div>
        <h5>{{ $article->category->name }}</h5>
        <small>
            Created at {{ date('d F Y', strtotime($article->created_at)) }}
            , by {{ $article->user->name . " " . $article->user->middle_name . " " . $article->user->last_name }}
        </small>
    </x-panel>
@stop