routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/', 'Home')->name('home');
Route::get('/dashboard', 'Dashboard')->name('dashboard')->middleware('auth');

Route::get('user/projects', 'UserProjectController@project')->name('user.project');
Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('/profile/update', 'ProfileController@update')->name('profile.update');
Route::get('/profile/edit/password', 'ProfileController@editPassword')->name('profile.password.edit');
Route::put('/profile/update/password', 'ProfileController@updatePassword')->name('profile.password.update');


Route::resource('leave', 'LeaveController');
Route::resource('status', 'StatusController')->except(['create', 'store']);
Route::resource('user', 'UserController');
Route::resource('project', 'ProjectController');
Route::resource('article', 'ArticleController');
Route::resource('category', 'CategoryController');
Route::resource('article-status', 'ArticleStatusController')->except(['create', 'store', 'edit', 'update']);

Route::put('article-status/{status}/accept', 'ArticleStatusController@accept')->name('article-status.accept');
Route::put('article-status/{status}/cancel', 'ArticleStatusController@cancel')->name('article-status.cancel');
Route::put('status/{status}/approve', 'StatusController@approve')->name('status.approve');
Route::put('status/{status}/decline', 'StatusController@decline')->name('status.decline');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $table = 'categories';

    protected $fillable = ['name'];

    public function article()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Tables\CategoryTableView;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return CategoryTableView
     */
    public function index()
    {
        //
        $category = Category::paginate();
        return CategoryTableView::make($category)->view('category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        //
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
        $category = new Category();
        $category->name = $request->name;
        $category->created_by = Auth::user()->id;
        $category->updated_by = Auth::user()->id;
        $category->save();

        return redirect()->back()->withSuccess('Category saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function edit(Category $category)
    {
        return view('category::edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, Category $category)
    {
        //
        $category['updated_by'] = Auth::user()->id;
        $category->update($request->all());

        return redirect()->back()->withSuccess('Category saved');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->back()->withSuccess('Category deleted');
    }
}

resources/views/category/_form.blade.php
{!! form()->text('name')->label('Name') !!}

{!! form()->action([
    form()->submit('Simpan'),
    form()->link('Batal', route('category.index'))
]) !!}

resources/views/category/create.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-backlink url="{{ route('category.index') }}"></x-backlink>

    <x-panel title="Tambah Category">
        {!! form()->post(route('category.store'))->horizontal()->multipart() !!}
        @include('category._form')
        {!! form()->close() !!}
    </x-panel>

@stop

resources/views/category/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-backlink url="{{ route('category.index') }}"></x-backlink>

    <x-panel title="Edit Category">
        {!! form()->bind($category)->put(route('category.update', $category->getKey()))->horizontal()->multipart() !!}
        @include('category._form')
        {!! form()->close() !!}
    </x-panel>

@stop

resources/views/category/index.blade.php
@extends('laravolt::layouts.app')

@section('content')


    <x-titlebar title="Category">
        <x-item>
            <x-link label="Tambah" icon="plus" url="{{ route('category.create') }}"></x-link>
        </x-item>
    </x-titlebar>

    {!! $table !!}
@stop