routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/', 'Home')->name('home');
Route::get('/dashboard', 'Dashboard')->name('dashboard')->middleware('auth');

Route::get('user/projects', 'UserProjectController@project')->name('user.project');
Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('/profile/update', 'ProfileController@update')->name('profile.update');
Route::get('/profile/edit/password', 'ProfileController@editPassword')->name('profile.password.edit');
Route::put('/profile/update/password', 'ProfileController@updatePassword')->name('profile.password.update');


Route::resource('leave', 'LeaveController');
Route::resource('status', 'StatusController')->except(['create', 'store']);
Route::resource('user', 'UserController');
Route::resource('project', 'ProjectController');
Route::resource('article', 'ArticleController');
Route::resource('category', 'CategoryController');
Route::resource('article-status', 'ArticleStatusController')->except(['create', 'store', 'edit', 'update']);

Route::put('article-status/{status}/accept', 'ArticleStatusController@accept')->name('article-status.accept');
Route::put('article-status/{status}/cancel', 'ArticleStatusController@cancel')->name('article-status.cancel');
Route::put('status/{status}/approve', 'StatusController@approve')->name('status.approve');
Route::put('status/{status}/decline', 'StatusController@decline')->name('status.decline');

app/Leave.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{
    //
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/LeaveController.php
<?php

namespace App\Http\Controllers;

use App\Leave;
use App\Tables\LeaveTableView;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class LeaveController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return LeaveTableView
     */
    public function index()
    {
        //
        $getLeaveOfUser = Auth::user()->leave;
        return (LeaveTableView::make($getLeaveOfUser))->view('leave.index');
    }

    /**
     * Show the form for crelating a new resource.
     *s
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        //
        return view('leave.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
        $leave = $request->all();
        $leave['status'] = 'pending';
        $leave['user_id'] = Auth::user()->id;
        Leave::create($leave);

        return redirect()->back()->withSuccess('Leave has been submitted!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
        $leave = Leave::find($id);
        return view('leave.show', ['leave' => $leave]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        //
        $leave = Leave::find($id);
        return view('leave.edit', ['leave' => $leave]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
        $leave = $request->all();
        Leave::find($id)->update($leave);

        return redirect()->back()->withSuccess('This submission has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
        $leave = Leave::find($id);
        $leave->delete();

        return redirect()->back()->withSuccess('This submission has been deleted!');
    }
}

resources/views/leave/create.blade.php
@extends('vendor.laravolt.layouts.app')
@section('content')

    <x-titlebar title="Leave Submission Form">
        <x-backlink url="{{ route('leave.index') }}"></x-backlink>
    </x-titlebar>

    <x-panel>
        {!! form()->open()->post()->route('leave.store')->horizontal() !!}

        {!! form()->dropdown('category', [
        'annual' => 'Annual',
        'sick' => 'Sick',
        'maternity' => 'Maternity',
        ])->label('Leave Category') !!}

        {!! form()->datepicker('start')->label('Starting Date') !!}
        {!! form()->textarea('information')->label('Leave Information') !!}

        {!! form()->action(form()->submit(__('laravolt::action.save'))) !!}
        {!! form()->close() !!}
    </x-panel>

@stop

resources/views/leave/edit.blade.php
@extends('vendor.laravolt.layouts.app')
@section('content')

    <x-titlebar title="Leave Submission Form">
        <x-backlink url="{{ route('leave.index') }}"></x-backlink>
    </x-titlebar>

    <x-panel>
        {!! form()->bind($leave)->open()->put()->action(route('leave.update', $leave->id)) !!}

        {!! form()->dropdown('category', [
        'annual' => 'Annual',
        'sick' => 'Sick',
        'maternity' => 'Maternity',
        ])->label('Leave Category') !!}

        {!! form()->date('start')->label('Starting Date') !!}
        {!! form()->textarea('information')->label('Leave Information') !!}

        {!! form()->action(form()->submit(__('laravolt::action.save'))) !!}
        {!! form()->close() !!}
    </x-panel>

@stop

resources/views/leave/index.blade.php
@extends('vendor.laravolt.layouts.app')
@section('content')
    <x-titlebar title="Leaves List">
        <div class="item">
            <x-link url="{{ route('leave.create') }}">
                <i class="icon plus"></i> @lang('laravolt::action.add')
            </x-link>
        </div>
    </x-titlebar>

    {!! $table !!}
@stop

resources/views/leave/show.blade.php
@extends('vendor.laravolt.layouts.app')
@section('content')

    <x-titlebar title="Leave Submission Form">
        <x-backlink url="{{ route('leave.index') }}"></x-backlink>
    </x-titlebar>

    <x-panel>
        {!! form()->open()->horizontal() !!}

        {!! form()->dropdown('category', [
        'annual' => 'Annual',
        'sick' => 'Sick',
        'maternity' => 'Maternity',
        ], $leave->category)->label('Leave Category')->disable() !!}

        {!! form()->text('start', date('d F Y', strtotime($leave->start)))->label('Starting Date')->disable() !!}
        {!! form()->textarea('information', $leave->information)->label('Leave Information')->disable() !!}

        {!! form()->close() !!}
    </x-panel>

@stop